# Hayden Horn IP5 - 3/22/22

In [3]:
import os 
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Self Awareness Data

In [4]:
data1=pd.read_csv('SADS.csv')

In [5]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Date                              64 non-null     object 
 1   Day                               64 non-null     object 
 2   Sleep Hour                        64 non-null     int64  
 3   Exercise Hour                     64 non-null     int64  
 4   Study Hour                        64 non-null     int64  
 5   StudyDS Hour                      64 non-null     int64  
 6   Work Hour                         64 non-null     int64  
 7   End of the day Feeling (0 to 10)  64 non-null     int64  
 8   Unnamed: 8                        0 non-null      float64
dtypes: float64(1), int64(6), object(2)
memory usage: 4.6+ KB


# 2.	Split your dataset into 48 entries for training, 12 entries for testing and 5 entries for validation. 

In [6]:
X=data1[['Day','Sleep Hour', 'Exercise Hour', 'Study Hour', 'StudyDS Hour', 'Work Hour']]
y=data1[['End of the day Feeling (0 to 10)']]

In [18]:
X= pd.get_dummies(data1[['Day','Sleep Hour', 'Exercise Hour', 'Study Hour', 'StudyDS Hour', 'Work Hour']],drop_first=True)
X.head()

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour  Day_Monday  \
0           8              2           3             2          2           0   
1           5              2           2             0          0           0   
2           6              0           0             0          0           0   
3           8              2           4             1          2           1   
4           8              2           1             0          0           0   

   Day_Saturday  Day_Sunday  Day_Thursday  Day_Tuesday  Day_Wednesday  
0             0           0             0            0              0  
1             1           0             0            0              0  
2             0           1             0            0              0  
3             0           0             0            0              0  
4             0           0             0            1              0

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=1/3,random_state=0)

In [9]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [10]:
print("Coefficient", regressor.coef_)

Coefficient [[-0.29115734 -1.16355144  0.3234443   0.70085488  0.1739331 ]]


In [11]:
print("intercept",regressor.intercept_)

intercept [10.0620003]


In [12]:
y_pred=regressor.predict(X_test)

# 8 hours of sleep, 2 hours of exercise, 4 study hours, 1 Study Ds hours, 0 work hours

In [13]:
regressor.predict([[8,2,4,1,0]])

C:\Users\hayde\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[7.40027077]])

# 7 hours of sleep, 0 hours of exercise, 2 study hours, 1 Study Ds hours, 2 work hours

In [14]:
regressor.predict([[7,0,2,1,2]])

C:\Users\hayde\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[9.71950858]])

# 6 hours of sleep, 4 hours of exercise, 0 study hours, 0 Study Ds hours, 2 work hours

In [15]:
regressor.predict([[6,4,0,0,2]])

C:\Users\hayde\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[4.00871666]])

# 5 hours of sleep, 2 hours of exercise, 2 study hours, 2 Study Ds hours, 2 work hours

In [16]:
regressor.predict([[5,2,2,2,2]])

C:\Users\hayde\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[8.67557526]])

# 6 hours of sleep, 4 hours of exercise, 2 study hours, 1 Study Ds hours, 2 work hours

In [17]:
regressor.predict([[6,4,2,1,2]])

C:\Users\hayde\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[5.35646015]])

In [19]:
from sklearn.metrics import r2_score
print('r2_score',r2_score(y_test,y_pred))

r2_score -0.37804378788553694
